dist: xenial
sudo: required
language: python
cache: pip

python:
  - 3.6

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - moreutils

services:
  - postgresql

env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
  - AWS_DEFAULT_OUTPUT=json
  - TERRAFORM_VERSION=0.12.0

install:
  - curl -Os https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - sudo unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin
  - pip install -r requirements-dev.txt

before_script:
  - source environment
  - make build-chalice-config init-db migrate-db load-test-data

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
