#!/usr/bin/env bash
set -a
PROJECT_ROOT=`pwd`
SERVICE_NAME='query'
DCP_DNS_DOMAIN='data.humancellatlas.org'
DEPLOYMENT_STAGE="${DEPLOYMENT_STAGE:-dev}"
AWS_DEFAULT_REGION='us-east-1'
API_HOST=${SERVICE_NAME}.${DEPLOYMENT_STAGE}.${DCP_DNS_DOMAIN}
set +a
