#!/bin/bash

set -euo pipefail

if [[ $# != 2 ]]; then
    echo "Usage: $(basename $0) daemon-name lambda-input-file"
    exit 1
fi

lambda_name="${APP_NAME}-${STAGE}-$1"
lambda_input_file=$2

raw_lambda_output="$(aws lambda invoke --function-name $lambda_name --invocation-type RequestResponse --payload "$(cat $lambda_input_file)" --log-type Tail /dev/stdout)"
lambda_output="$(echo $raw_lambda_output | jq -r '. | select(.LogResult)')"

# lambda output is occasionally malformed as appended JSON objects: {"wrong_obj": ... }{"LogResult": ...}
# This selects the object we wish to examine for error
echo "$lambda_output" | jq -r .LogResult | base64 --decode

[[ $(echo "$lambda_output" | jq -r .FunctionError) == null ]]
