import csv

with open('cells.tsv') as tsvfile:
  reader = csv.DictReader(tsvfile, dialect='excel-tab')

  for row in reader:
    while i < 50:
        print(row)

cellkey
genes_detected
file_uuid
file_version
total_umis
emptydrops_is_cell
barcode	cell_suspension.provenance.document_id
specimen_from_organism.provenance.document_id
derived_organ_ontology
derived_organ_label	derived_organ_parts_ontology
derived_organ_parts_label
cell_suspension.genus_species.ontology
cell_suspension.genus_species.ontology_label
donor_organism.provenance.document_id
donor_organism.human_specific.ethnicity.ontology
donor_organism.human_specific.ethnicity.ontology_label
donor_organism.diseases.ontology
donor_organism.diseases.ontology_label
donor_organism.development_stage.ontology
donor_organism.development_stage.ontology_label
donor_organism.sex
donor_organism.is_living
specimen_from_organism.organ.ontology
specimen_from_organism.organ.ontology_label
specimen_from_organism.organ_parts.ontology
specimen_from_organism.organ_parts.ontology_label
library_preparation_protocol.provenance.document_id
library_preparation_protocol.input_nucleic_acid_molecule.ontology
library_preparation_protocol.input_nucleic_acid_molecule.ontology_label
library_preparation_protocol.library_construction_method.ontology
library_preparation_protocol.library_construction_method.ontology_label
library_preparation_protocol.end_bias
library_preparation_protocol.strand
project.provenance.document_id
project.project_core.project_short_name
project.project_core.project_title
analysis_protocol.provenance.document_id
dss_bundle_fqid	bundle_uuid	bundle_version
analysis_protocol.protocol_core.protocol_id
analysis_working_group_approval_status