# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

# Default Provider
provider "aws" {
  version             = "~> 1.27.0"
  region              = "us-east-1"
  profile             = "hca-prod"
  allowed_account_ids = [109067257620]
}

# Aliased Providers (for doing things in every region).

terraform {
  required_version = "=0.11.7"

  backend "s3" {
    bucket  = "org-humancellatlas-634134578715-terraform"
    key     = "terraform/query-service/accounts/hca-prod.tfstate"
    encrypt = true
    region  = "us-east-1"
    profile = "hca-id"
  }
}

variable "project" {
  type    = "string"
  default = "query-service"
}

variable "region" {
  type    = "string"
  default = "us-east-1"
}

variable "aws_profile" {
  type    = "string"
  default = "hca-prod"
}

variable "owner" {
  type    = "string"
  default = "mweiden@chanzuckerberg.com"
}

variable "aws_accounts" {
  type = "map"

  default = {
    hca-prod = 109067257620

    humancellatlas = 861229788715
  }
}

data "terraform_remote_state" "global" {
  backend = "s3"

  config {
    bucket  = "org-humancellatlas-634134578715-terraform"
    key     = "terraform/query-service/global.tfstate"
    region  = "us-east-1"
    profile = "hca-id"
  }
}
