# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "database" {
  source              = "../../../modules/database"
  db_instance_count   = "${local.db_instance_count}"
  db_password         = "${local.db_password}"
  db_username         = "${local.db_username}"
  env                 = "${local.env}"
  lb_subnet_ids       = "${local.lb_subnet_ids}"
  pgbouncer_subnet_id = "${local.pgbouncer_subnet_id}"
  vpc_id              = "${local.vpc_id}"
}
