#!/usr/bin/env python3
import argparse
import os
import sys

pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '../..'))  # noqa
sys.path.insert(0, pkg_root)  # noqa

from query.lib.config import Config
from query.lib.logger import logger
from query.lib.db.database import PostgresDatabase

NAME = sys.argv[0].split('/')[-1]
CLI = argparse.ArgumentParser(
    description=f"`{NAME}` is an admin tool for database operations on the Query Service."
)
CLI.add_argument(
    'database',
    choices=['serve', 'test'],
    help="The serve database is the database that serves traffic, the test database is used for, well, tests."
)
CLI.add_argument(
    'action',
    choices=['init', 'destroy'],
    help="DANGER: clearing the database will clear out all tables. Initializing resets the initial database schemas."
)

if __name__ == '__main__':
    options = CLI.parse_args(sys.argv[1:])

    db_uri = {
        'serve': Config.serve_database_uri,
        'test': Config.test_database_uri
    }[options.database]

    db = PostgresDatabase(db_uri)

    if options.action == 'init':
        with db.transaction() as (_, tables):
            tables.files.initialize()
            tables.bundles.initialize()
            tables.bundles_files.initialize()
            tables.job_status.initialize()

    elif options.action == 'destroy':
        conf = input("Are you sure that you want to do this? [Y/n] ")
        if conf != "Y":
            logger.info("Ok, whew.")
            sys.exit(0)
        with db.transaction() as (_, tables):
            for table in [tables.bundles_files, tables.files, tables.bundles, tables.job_status]:
                try:
                    table.destroy()
                    logger.info(f"Dropped table: {table}")
                except:
                    logger.exception(f"Could not drop table: {table}")

    logger.info(f"Completed action {options.action} on database: {options.database}")
