"""empty message

Revision ID: 38ca016b4425
Revises: 7597ca0971e5
Create Date: 2019-05-08 23:29:36.596896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ca016b4425'
down_revision = '7597ca0971e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_bundle', 'bundles', ['fqid'])
    op.create_unique_constraint('unique_file', 'files', ['fqid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_file', 'files', type_='unique')
    op.drop_constraint('unique_bundle', 'bundles', type_='unique')
    # ### end Alembic commands ###
