"""add unique req to process_process combo. I think this is going to be a breaking change/require dropping and
reinitializing the db

Revision ID: 88bab7754636
Revises: e2b45add6f68
Create Date: 2019-07-26 11:28:06.281752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88bab7754636'
down_revision = '7597ca0971e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unq_process_combo', 'process_join_table', ['child_process_uuid', 'parent_process_uuid'])
    op.execute(
        """
        CREATE OR REPLACE RULE process_join_table_ignore_duplicate_inserts AS
            ON INSERT TO process_join_table
                WHERE EXISTS (
                  SELECT 1
                FROM process_join_table
                WHERE child_process_uuid = NEW.child_process_uuid
                AND parent_process_uuid = NEW.parent_process_uuid
            )
            DO INSTEAD NOTHING;
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unq_process_combo', 'process_join_table', type_='unique')
    op.execute("DROP RULE IF EXISTS process_join_table_ignore_duplicate_inserts ON process_join_table;")

    # ### end Alembic commands ###
