"""rename processes to processes_for_graph

Revision ID: 9fa7918d332b
Revises: 7597ca0971e5
Create Date: 2019-08-02 12:02:51.857794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fa7918d332b'
down_revision = '7597ca0971e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('processes', 'processes_for_graph')
    op.execute(
        """
        CREATE OR REPLACE RULE process_table_ignore_duplicate_inserts AS
            ON INSERT TO processes_for_graph
                WHERE EXISTS (
                  SELECT 1
                FROM processes_for_graph
                WHERE process_uuid = NEW.process_uuid
            )
            DO INSTEAD NOTHING;
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP RULE IF EXISTS process_table_ignore_duplicate_inserts ON processes_for_graph;")
    op.rename_table('processes_for_graph', 'processes')
    # ### end Alembic commands ###
