"""create indices

Revision ID: b56789b3d784
Revises: e2b45add6f68
Create Date: 2019-08-06 11:28:21.050690

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b56789b3d784'
down_revision = 'e2b45add6f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bundle_file_links_bundle_fqid'), 'bundle_file_links', ['bundle_fqid'], unique=False)
    op.create_index(op.f('ix_bundle_file_links_file_fqid'), 'bundle_file_links', ['file_fqid'], unique=False)
    op.create_index(op.f('ix_bundles_all_versions_fqid'), 'bundles_all_versions', ['fqid'], unique=True)
    op.create_index(op.f('ix_bundles_all_versions_uuid'), 'bundles_all_versions', ['uuid'], unique=False)
    op.create_index(op.f('ix_bundles_all_versions_version'), 'bundles_all_versions', ['version'], unique=False)
    op.create_index(op.f('ix_files_all_versions_fqid'), 'files_all_versions', ['fqid'], unique=True)
    op.create_index(op.f('ix_files_all_versions_uuid'), 'files_all_versions', ['uuid'], unique=False)
    op.create_index(op.f('ix_files_all_versions_version'), 'files_all_versions', ['version'], unique=False)
    op.create_index(op.f('ix_process_file_join_table_process_uuid'), 'process_file_join_table', ['process_uuid'],
                    unique=False)
    op.create_index(op.f('ix_process_join_table_child_process_uuid'), 'process_join_table', ['child_process_uuid'],
                    unique=False)
    op.create_index(op.f('ix_process_join_table_parent_process_uuid'), 'process_join_table', ['parent_process_uuid'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_process_join_table_parent_process_uuid'), table_name='process_join_table')
    op.drop_index(op.f('ix_process_join_table_child_process_uuid'), table_name='process_join_table')
    op.drop_index(op.f('ix_process_file_join_table_process_uuid'), table_name='process_file_join_table')
    op.drop_index(op.f('ix_files_all_versions_version'), table_name='files_all_versions')
    op.drop_index(op.f('ix_files_all_versions_uuid'), table_name='files_all_versions')
    op.drop_index(op.f('ix_files_all_versions_fqid'), table_name='files_all_versions')
    op.drop_index(op.f('ix_bundles_all_versions_version'), table_name='bundles_all_versions')
    op.drop_index(op.f('ix_bundles_all_versions_uuid'), table_name='bundles_all_versions')
    op.drop_index(op.f('ix_bundles_all_versions_fqid'), table_name='bundles_all_versions')
    op.drop_index(op.f('ix_bundle_file_links_file_fqid'), table_name='bundle_file_links')
    op.drop_index(op.f('ix_bundle_file_links_bundle_fqid'), table_name='bundle_file_links')
    # ### end Alembic commands ###
