"""empty message

Revision ID: e18b84419e8c
Revises: ec105347982a
Create Date: 2019-12-10 23:53:29.507649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18b84419e8c'
down_revision = 'ec105347982a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('accession_id', sa.String(), nullable=True))
    op.add_column('features', sa.Column('id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'features', 'accessions', ['accession_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'features', type_='foreignkey')
    op.drop_column('features', 'id')
    op.drop_column('features', 'accession_id')
    # ### end Alembic commands ###
