"""empty message

Revision ID: e1a0543feac6
Revises: e5a3141a178d
Create Date: 2019-10-22 16:56:32.935427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1a0543feac6'
down_revision = '132698d15453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files_all_versions', sa.Column('flat_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files_all_versions', 'flat_body')
    # ### end Alembic commands ###
