""" add project to process file link

Revision ID: e7d502547475
Revises: e5a3141a178d
Create Date: 2019-09-25 10:20:15.551074

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e7d502547475'
down_revision = 'e5a3141a178d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_file_join_table', sa.Column('project_fqid', sa.String(), nullable=True))
    op.create_index(op.f('ix_process_file_join_table_file_uuid'), 'process_file_join_table', ['file_uuid'],
                    unique=False)
    op.create_index(op.f('ix_process_file_join_table_project_fqid'), 'process_file_join_table', ['project_fqid'],
                    unique=False)
    op.drop_constraint('process_file_connection_type_uc', 'process_file_join_table', type_='unique')
    op.create_unique_constraint('process_file_connection_type_uc', 'process_file_join_table',
                                ['process_uuid', 'process_file_connection_type', 'file_uuid', 'project_fqid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('process_file_connection_type_uc', 'process_file_join_table', type_='unique')
    op.create_unique_constraint('process_file_connection_type_uc', 'process_file_join_table',
                                ['process_uuid', 'process_file_connection_type', 'file_uuid'])
    op.drop_index(op.f('ix_process_file_join_table_project_fqid'), table_name='process_file_join_table')
    op.drop_index(op.f('ix_process_file_join_table_file_uuid'), table_name='process_file_join_table')
    op.drop_column('process_file_join_table', 'project_fqid')
    # ### end Alembic commands ###
