"""empty message

Revision ID: ec105347982a
Revises: 799eadf9234d
Create Date: 2019-12-10 23:22:23.257626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec105347982a'
down_revision = '799eadf9234d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barcodes', sa.Column('barcode_string', sa.String(), nullable=True))
    op.add_column('cells', sa.Column('barcode', sa.String(), nullable=True))
    op.add_column('cells', sa.Column('cellkey', sa.String(), nullable=True))
    op.add_column('cells', sa.Column('file_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('cells_sequence_file_uuid_fkey', 'cells', type_='foreignkey')
    op.create_foreign_key(None, 'cells', 'files', ['file_uuid'], ['uuid'])
    op.drop_column('cells', 'sequence_file_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cells', sa.Column('sequence_file_uuid', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cells', type_='foreignkey')
    op.create_foreign_key('cells_sequence_file_uuid_fkey', 'cells', 'sequence_files', ['sequence_file_uuid'], ['uuid'])
    op.drop_column('cells', 'file_uuid')
    op.drop_column('cells', 'cellkey')
    op.drop_column('cells', 'barcode')
    op.drop_column('barcodes', 'barcode_string')
    # ### end Alembic commands ###
